### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd
# import numpy as np
import numpy as np

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.  
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Calculate the percentage of students who passed math **and** reading (% Overall Passing)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [2]:
#Calculate RawData

countschools = school_data['school_name'].count()
countstudents = student_data['Student ID'].count()

total_budget = school_data["budget"].agg(['sum'])
tot_budget = total_budget
av_mathscore = student_data['math_score'].mean()
av_readscore = student_data['reading_score'].mean()
schooltype = school_data['type'].unique()

w=len(school_data_complete[(school_data_complete['math_score']>=70)])
r=len(school_data_complete[(school_data_complete['reading_score']>=70)])
p=len(school_data_complete[(school_data_complete['math_score']>=70) & (school_data_complete['reading_score']>=70)])

x = w / countstudents*100
y = r / countstudents*100
z = p / countstudents*100


# initialise data of lists.
data = {'Item':['Total Schools','Total Students','Total Budget','Average Math Score','Average Reading Score', '% Passing Math', '% Passing Reading', '% Overall Passing' ], 'Value':[countschools, countstudents, tot_budget, av_mathscore, av_readscore,x,y,z]}

# Create DataFrame

sc_summary_df = pd.DataFrame(data)
sc_summary_df

                    Item                                       Value
0          Total Schools                                          15
1         Total Students                                       39170
2           Total Budget  sum    24649428
Name: budget, dtype: int64
3     Average Math Score                                   78.985371
4  Average Reading Score                                    81.87784
5         % Passing Math                                   74.980853
6      % Passing Reading                                   85.805463
7      % Overall Passing                                   65.172326

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * % Overall Passing (The percentage of students that passed math **and** reading.)
  
* Create a dataframe to hold the above results

In [3]:
#take the all data, create a new copy
school_data_complete2 = school_data_complete.copy()

school_data_complete2['Per Student Budget'] = school_data_complete2['budget'] / school_data_complete2['size']
                                                                
def math_pass(value):
    if value < 70:
        return 0
    elif value >69:
        return 1
    
school_data_complete2['math_pass'] = school_data_complete2['math_score'].map(math_pass)

def read_pass(value):
    if value < 70:
        return 0
    elif value >69:
        return 1
    
school_data_complete2['read_pass'] = school_data_complete2['reading_score'].map(read_pass)

def both_pass(row):
    if row['math_pass'] == 1 & row['read_pass'] == 1: 
                
        val = 1    
    else:
        val = 0
    return val

school_data_complete2['all_pass'] = school_data_complete2.apply(both_pass, axis=1)

#convert %
school_data_complete2['% Passing Math'] = school_data_complete2['math_pass'] * 100
school_data_complete2['% Passing Reading'] = school_data_complete2['read_pass'] * 100
school_data_complete2['% Overall Passing'] = school_data_complete2['all_pass'] * 100


#Column management 
#remove unwanted columns
school_data_complete2 = school_data_complete2.drop(columns=['read_pass'])
school_data_complete2 = school_data_complete2.drop(columns=['all_pass'])
school_data_complete2 = school_data_complete2.drop(columns=['math_pass'])
school_data_complete2 = school_data_complete2.drop(columns=['Student ID'])
school_data_complete2 = school_data_complete2.drop(columns=['School ID'])


school2 = school_data_complete2.groupby(['school_name','type']).agg('mean').sort_values(by=['budget'],ascending=False)
school2

,,reading_score,math_score,size,budget,Per Student Budget,% Passing Math,% Passing Reading,% Overall Passing
school_name,type,,,,,,,,
Bailey High School,District,81.033963,77.048432,4976.0,3124928.0,628.0,66.680064,81.933280,54.642283
Johnson High School,District,80.966394,77.072464,4761.0,3094650.0,650.0,66.057551,81.222432,53.539172
Hernandez High School,District,80.934412,77.289752,4635.0,3022020.0,652.0,66.752967,80.862999,53.527508
Rodriguez High School,District,80.744686,76.842711,3999.0,2547363.0,637.0,66.366592,80.220055,52.988247
Huang High School,District,81.182722,76.629414,2917.0,1910635.0,655.0,65.683922,81.316421,53.513884
Figueroa High School,District,81.158020,76.711767,2949.0,1884411.0,639.0,65.988471,80.739234,53.204476
Ford High School,District,80.746258,77.102592,2739.0,1763916.0,644.0,68.309602,79.299014,54.289887
Wilson High School,Charter,83.989488,83.274201,2283.0,1319574.0,578.0,93.867718,96.539641,90.582567
Cabrera High School,Charter,83.975780,83.061895,1858.0,1081356.0,582.0,94.133477,97.039828,91.334769
Shelton High School,Charter,83.725724,83.359455,1761.0,1056600.0,600.0,93.867121,95.854628,89.892107
Wright High School,Charter,83.955000,83.682222,1800.0,1049400.0,583.0,93.333333,96.611111,90.333333
Thomas High School,Charter,83.848930,83.418349,1635.0,1043130.0,638.0,93.272171,97.308869,90.948012
Griffin High School,Charter,83.816757,83.351499,1468.0,917500.0,625.0,93.392371,97.138965,90.599455
Pena High School,Charter,84.044699,83.839917,962.0,585858.0,609.0,94.594595,95.945946,90.540541
Holden High School,Charter,83.814988,83.803279,427.0,248087.0,581.0,92.505855,96.252927,89.227166

## Top Performing Schools (By % Overall Passing)

* Sort and display the top five performing schools by % overall passing.

In [4]:
school_data_complete2.groupby(['school_name','type']).agg('mean').sort_values(by=['% Overall Passing'],ascending=False)

,,reading_score,math_score,size,budget,Per Student Budget,% Passing Math,% Passing Reading,% Overall Passing
school_name,type,,,,,,,,
Cabrera High School,Charter,83.975780,83.061895,1858.0,1081356.0,582.0,94.133477,97.039828,91.334769
Thomas High School,Charter,83.848930,83.418349,1635.0,1043130.0,638.0,93.272171,97.308869,90.948012
Griffin High School,Charter,83.816757,83.351499,1468.0,917500.0,625.0,93.392371,97.138965,90.599455
Wilson High School,Charter,83.989488,83.274201,2283.0,1319574.0,578.0,93.867718,96.539641,90.582567
Pena High School,Charter,84.044699,83.839917,962.0,585858.0,609.0,94.594595,95.945946,90.540541
Wright High School,Charter,83.955000,83.682222,1800.0,1049400.0,583.0,93.333333,96.611111,90.333333
Shelton High School,Charter,83.725724,83.359455,1761.0,1056600.0,600.0,93.867121,95.854628,89.892107
Holden High School,Charter,83.814988,83.803279,427.0,248087.0,581.0,92.505855,96.252927,89.227166
Bailey High School,District,81.033963,77.048432,4976.0,3124928.0,628.0,66.680064,81.933280,54.642283
Ford High School,District,80.746258,77.102592,2739.0,1763916.0,644.0,68.309602,79.299014,54.289887
Johnson High School,District,80.966394,77.072464,4761.0,3094650.0,650.0,66.057551,81.222432,53.539172
Hernandez High School,District,80.934412,77.289752,4635.0,3022020.0,652.0,66.752967,80.862999,53.527508
Huang High School,District,81.182722,76.629414,2917.0,1910635.0,655.0,65.683922,81.316421,53.513884
Figueroa High School,District,81.158020,76.711767,2949.0,1884411.0,639.0,65.988471,80.739234,53.204476
Rodriguez High School,District,80.744686,76.842711,3999.0,2547363.0,637.0,66.366592,80.220055,52.988247

## Bottom Performing Schools (By % Overall Passing)

* Sort and display the five worst-performing schools by % overall passing.

In [5]:
school_data_complete2.groupby(['school_name','type']).agg('mean').sort_values(by=['% Overall Passing'],ascending=True)

,,reading_score,math_score,size,budget,Per Student Budget,% Passing Math,% Passing Reading,% Overall Passing
school_name,type,,,,,,,,
Rodriguez High School,District,80.744686,76.842711,3999.0,2547363.0,637.0,66.366592,80.220055,52.988247
Figueroa High School,District,81.158020,76.711767,2949.0,1884411.0,639.0,65.988471,80.739234,53.204476
Huang High School,District,81.182722,76.629414,2917.0,1910635.0,655.0,65.683922,81.316421,53.513884
Hernandez High School,District,80.934412,77.289752,4635.0,3022020.0,652.0,66.752967,80.862999,53.527508
Johnson High School,District,80.966394,77.072464,4761.0,3094650.0,650.0,66.057551,81.222432,53.539172
Ford High School,District,80.746258,77.102592,2739.0,1763916.0,644.0,68.309602,79.299014,54.289887
Bailey High School,District,81.033963,77.048432,4976.0,3124928.0,628.0,66.680064,81.933280,54.642283
Holden High School,Charter,83.814988,83.803279,427.0,248087.0,581.0,92.505855,96.252927,89.227166
Shelton High School,Charter,83.725724,83.359455,1761.0,1056600.0,600.0,93.867121,95.854628,89.892107
Wright High School,Charter,83.955000,83.682222,1800.0,1049400.0,583.0,93.333333,96.611111,90.333333
Pena High School,Charter,84.044699,83.839917,962.0,585858.0,609.0,94.594595,95.945946,90.540541
Wilson High School,Charter,83.989488,83.274201,2283.0,1319574.0,578.0,93.867718,96.539641,90.582567
Griffin High School,Charter,83.816757,83.351499,1468.0,917500.0,625.0,93.392371,97.138965,90.599455
Thomas High School,Charter,83.848930,83.418349,1635.0,1043130.0,638.0,93.272171,97.308869,90.948012
Cabrera High School,Charter,83.975780,83.061895,1858.0,1081356.0,582.0,94.133477,97.039828,91.334769

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

In [6]:
school_data_complete3 = school_data_complete.copy()
school_data_complete3.rename(columns = {'School ID':'School_ID'}, inplace = True)
school_data_complete4 = school_data_complete3.copy()

# create list of grades
gradelist = ['9th','10th','11th','12th']
schoollist = ['Huang High School','Figueroa High School','Shelton High School','Hernandez High School','Griffin High School','Wilson High School','Cabrera High School','Bailey High School','Holden High School','Pena High School','Wright High School','Rodriguez High School','Johnson High School','Ford High School','Thomas High School']

sc_summary_df = pd.DataFrame(columns=['School_Name','Grade','Average Math Score'])

# for loop to go through the search lists
for i in schoollist:
   
    for j in gradelist:

            filter1 = school_data_complete4[(school_data_complete4.school_name == i) & (school_data_complete4.grade == j)]
                        
            av_mathscore = filter1['math_score'].mean()
                      
            sc_summary_df.loc[len(sc_summary_df)] = [i, j, av_mathscore]
sc_summary_df

              School_Name Grade  Average Math Score
0       Huang High School   9th           77.027251
1       Huang High School  10th           75.908735
2       Huang High School  11th           76.446602
3       Huang High School  12th           77.225641
4    Figueroa High School   9th           76.403037
5    Figueroa High School  10th           76.539974
6    Figueroa High School  11th           76.884344
7    Figueroa High School  12th           77.151369
8     Shelton High School   9th           83.420755
9     Shelton High School  10th           82.917411
10    Shelton High School  11th           83.383495
11    Shelton High School  12th           83.778976
12  Hernandez High School   9th           77.438495
13  Hernandez High School  10th           77.337408
14  Hernandez High School  11th           77.136029
15  Hernandez High School  12th           77.186567
16    Griffin High School   9th           82.044010
17    Griffin High School  10th           84.229064
18    Griffin High School  11th           83.842105
19    Griffin High School  12th           83.356164
20     Wilson High School   9th           83.085578
21     Wilson High School  10th           83.724422
22     Wilson High School  11th           83.195326
23     Wilson High School  12th           83.035794
24    Cabrera High School   9th           83.094697
25    Cabrera High School  10th           83.154506
26    Cabrera High School  11th           82.765560
27    Cabrera High School  12th           83.277487
28     Bailey High School   9th           77.083676
29     Bailey High School  10th           76.996772
30     Bailey High School  11th           77.515588
31     Bailey High School  12th           76.492218
32     Holden High School   9th           83.787402
33     Holden High School  10th           83.429825
34     Holden High School  11th           85.000000
35     Holden High School  12th           82.855422
36       Pena High School   9th           83.625455
37       Pena High School  10th           83.372000
38       Pena High School  11th           84.328125
39       Pena High School  12th           84.121547
40     Wright High School   9th           83.264706
41     Wright High School  10th           84.010288
42     Wright High School  11th           83.836782
43     Wright High School  12th           83.644986
44  Rodriguez High School   9th           76.859966
45  Rodriguez High School  10th           76.612500
46  Rodriguez High School  11th           76.395626
47  Rodriguez High School  12th           77.690748
48    Johnson High School   9th           77.187857
49    Johnson High School  10th           76.691117
50    Johnson High School  11th           77.491653
51    Johnson High School  12th           76.863248
52       Ford High School   9th           77.361345
53       Ford High School  10th           77.672316
54       Ford High School  11th           76.918058
55       Ford High School  12th           76.179963
56     Thomas High School   9th           83.590022
57     Thomas High School  10th           83.087886
58     Thomas High School  11th           83.498795
59     Thomas High School  12th           83.497041

## Reading Score by Grade

* Perform the same operations as above for reading scores

In [7]:
school_data_complete3 = school_data_complete.copy()
school_data_complete3.rename(columns = {'School ID':'School_ID'}, inplace = True)
school_data_complete5 = school_data_complete3.copy()

# create list of grades
gradelist = ['9th','10th','11th','12th']
schoollist = ['Huang High School','Figueroa High School','Shelton High School','Hernandez High School','Griffin High School','Wilson High School','Cabrera High School','Bailey High School','Holden High School','Pena High School','Wright High School','Rodriguez High School','Johnson High School','Ford High School','Thomas High School']

sc_summary2_df = pd.DataFrame(columns=['School_Name','Grade','Average Reading Score %'])

# for loop to go through the search lists
for i in schoollist:
   
    for j in gradelist:

            filter1 = school_data_complete5[(school_data_complete5.school_name == i) & (school_data_complete5.grade == j)]
                        
            av_readscore = filter1['reading_score'].mean()
                      
            sc_summary2_df.loc[len(sc_summary2_df)] = [i, j, av_readscore]
sc_summary2_df

              School_Name Grade  Average Reading Score %
0       Huang High School   9th                81.290284
1       Huang High School  10th                81.512386
2       Huang High School  11th                81.417476
3       Huang High School  12th                80.305983
4    Figueroa High School   9th                81.198598
5    Figueroa High School  10th                81.408912
6    Figueroa High School  11th                80.640339
7    Figueroa High School  12th                81.384863
8     Shelton High School   9th                84.122642
9     Shelton High School  10th                83.441964
10    Shelton High School  11th                84.373786
11    Shelton High School  12th                82.781671
12  Hernandez High School   9th                80.866860
13  Hernandez High School  10th                80.660147
14  Hernandez High School  11th                81.396140
15  Hernandez High School  12th                80.857143
16    Griffin High School   9th                83.369193
17    Griffin High School  10th                83.706897
18    Griffin High School  11th                84.288089
19    Griffin High School  12th                84.013699
20     Wilson High School   9th                83.939778
21     Wilson High School  10th                84.021452
22     Wilson High School  11th                83.764608
23     Wilson High School  12th                84.317673
24    Cabrera High School   9th                83.676136
25    Cabrera High School  10th                84.253219
26    Cabrera High School  11th                83.788382
27    Cabrera High School  12th                84.287958
28     Bailey High School   9th                81.303155
29     Bailey High School  10th                80.907183
30     Bailey High School  11th                80.945643
31     Bailey High School  12th                80.912451
32     Holden High School   9th                83.677165
33     Holden High School  10th                83.324561
34     Holden High School  11th                83.815534
35     Holden High School  12th                84.698795
36       Pena High School   9th                83.807273
37       Pena High School  10th                83.612000
38       Pena High School  11th                84.335938
39       Pena High School  12th                84.591160
40     Wright High School   9th                83.833333
41     Wright High School  10th                83.812757
42     Wright High School  11th                84.156322
43     Wright High School  12th                84.073171
44  Rodriguez High School   9th                80.993127
45  Rodriguez High School  10th                80.629808
46  Rodriguez High School  11th                80.864811
47  Rodriguez High School  12th                80.376426
48    Johnson High School   9th                81.260714
49    Johnson High School  10th                80.773431
50    Johnson High School  11th                80.616027
51    Johnson High School  12th                81.227564
52       Ford High School   9th                80.632653
53       Ford High School  10th                81.262712
54       Ford High School  11th                80.403642
55       Ford High School  12th                80.662338
56     Thomas High School   9th                83.728850
57     Thomas High School  10th                84.254157
58     Thomas High School  11th                83.585542
59     Thomas High School  12th                83.831361

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [8]:
 
school2
groupsort = school2[['Per Student Budget','size','math_score','reading_score','% Passing Math','% Passing Reading', '% Overall Passing']]

bins = [0,585,630,645,680]
group_names = ['<585', '585-630', "630-645", "645-680"]

groupsort["Spending Ranges (per Student)"] = pd.cut(groupsort["Per Student Budget"], bins, labels=group_names, include_lowest=True)

#groupsort.groupby(['Spending Ranges (per Student']).sort_values(by=['Per Student Budget'],ascending=False)
groupsort

,,Per Student Budget,size,math_score,reading_score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (per Student)
school_name,type,,,,,,,,
Bailey High School,District,628.0,4976.0,77.048432,81.033963,66.680064,81.933280,54.642283,585-630
Johnson High School,District,650.0,4761.0,77.072464,80.966394,66.057551,81.222432,53.539172,645-680
Hernandez High School,District,652.0,4635.0,77.289752,80.934412,66.752967,80.862999,53.527508,645-680
Rodriguez High School,District,637.0,3999.0,76.842711,80.744686,66.366592,80.220055,52.988247,630-645
Huang High School,District,655.0,2917.0,76.629414,81.182722,65.683922,81.316421,53.513884,645-680
Figueroa High School,District,639.0,2949.0,76.711767,81.158020,65.988471,80.739234,53.204476,630-645
Ford High School,District,644.0,2739.0,77.102592,80.746258,68.309602,79.299014,54.289887,630-645
Wilson High School,Charter,578.0,2283.0,83.274201,83.989488,93.867718,96.539641,90.582567,<585
Cabrera High School,Charter,582.0,1858.0,83.061895,83.975780,94.133477,97.039828,91.334769,<585
Shelton High School,Charter,600.0,1761.0,83.359455,83.725724,93.867121,95.854628,89.892107,585-630
Wright High School,Charter,583.0,1800.0,83.682222,83.955000,93.333333,96.611111,90.333333,<585
Thomas High School,Charter,638.0,1635.0,83.418349,83.848930,93.272171,97.308869,90.948012,630-645
Griffin High School,Charter,625.0,1468.0,83.351499,83.816757,93.392371,97.138965,90.599455,585-630
Pena High School,Charter,609.0,962.0,83.839917,84.044699,94.594595,95.945946,90.540541,585-630
Holden High School,Charter,581.0,427.0,83.803279,83.814988,92.505855,96.252927,89.227166,<585

## Scores by School Size

* Perform the same operations as above, based on school size.

In [9]:

groupsort = school2[['Per Student Budget','size','math_score','reading_score','% Passing Math','% Passing Reading', '% Overall Passing']]
bins = [0,1000,2000,5000]
group_names = ['Small(<1000)', 'Medium(1000-2000)', 'Large(2000-5000)']

groupsort["School Size"] = pd.cut(groupsort[("size")], bins, labels=group_names, include_lowest=True)

groupsort

,,Per Student Budget,size,math_score,reading_score,% Passing Math,% Passing Reading,% Overall Passing,School Size
school_name,type,,,,,,,,
Bailey High School,District,628.0,4976.0,77.048432,81.033963,66.680064,81.933280,54.642283,Large(2000-5000)
Johnson High School,District,650.0,4761.0,77.072464,80.966394,66.057551,81.222432,53.539172,Large(2000-5000)
Hernandez High School,District,652.0,4635.0,77.289752,80.934412,66.752967,80.862999,53.527508,Large(2000-5000)
Rodriguez High School,District,637.0,3999.0,76.842711,80.744686,66.366592,80.220055,52.988247,Large(2000-5000)
Huang High School,District,655.0,2917.0,76.629414,81.182722,65.683922,81.316421,53.513884,Large(2000-5000)
Figueroa High School,District,639.0,2949.0,76.711767,81.158020,65.988471,80.739234,53.204476,Large(2000-5000)
Ford High School,District,644.0,2739.0,77.102592,80.746258,68.309602,79.299014,54.289887,Large(2000-5000)
Wilson High School,Charter,578.0,2283.0,83.274201,83.989488,93.867718,96.539641,90.582567,Large(2000-5000)
Cabrera High School,Charter,582.0,1858.0,83.061895,83.975780,94.133477,97.039828,91.334769,Medium(1000-2000)
Shelton High School,Charter,600.0,1761.0,83.359455,83.725724,93.867121,95.854628,89.892107,Medium(1000-2000)
Wright High School,Charter,583.0,1800.0,83.682222,83.955000,93.333333,96.611111,90.333333,Medium(1000-2000)
Thomas High School,Charter,638.0,1635.0,83.418349,83.848930,93.272171,97.308869,90.948012,Medium(1000-2000)
Griffin High School,Charter,625.0,1468.0,83.351499,83.816757,93.392371,97.138965,90.599455,Medium(1000-2000)
Pena High School,Charter,609.0,962.0,83.839917,84.044699,94.594595,95.945946,90.540541,Small(<1000)
Holden High School,Charter,581.0,427.0,83.803279,83.814988,92.505855,96.252927,89.227166,Small(<1000)

## Scores by School Type

* Perform the same operations as above, based on school type

In [10]:
groupsort = school2[['Per Student Budget','size','math_score','reading_score','% Passing Math','% Passing Reading', '% Overall Passing']]
groupsort

,,Per Student Budget,size,math_score,reading_score,% Passing Math,% Passing Reading,% Overall Passing
school_name,type,,,,,,,
Bailey High School,District,628.0,4976.0,77.048432,81.033963,66.680064,81.933280,54.642283
Johnson High School,District,650.0,4761.0,77.072464,80.966394,66.057551,81.222432,53.539172
Hernandez High School,District,652.0,4635.0,77.289752,80.934412,66.752967,80.862999,53.527508
Rodriguez High School,District,637.0,3999.0,76.842711,80.744686,66.366592,80.220055,52.988247
Huang High School,District,655.0,2917.0,76.629414,81.182722,65.683922,81.316421,53.513884
Figueroa High School,District,639.0,2949.0,76.711767,81.158020,65.988471,80.739234,53.204476
Ford High School,District,644.0,2739.0,77.102592,80.746258,68.309602,79.299014,54.289887
Wilson High School,Charter,578.0,2283.0,83.274201,83.989488,93.867718,96.539641,90.582567
Cabrera High School,Charter,582.0,1858.0,83.061895,83.975780,94.133477,97.039828,91.334769
Shelton High School,Charter,600.0,1761.0,83.359455,83.725724,93.867121,95.854628,89.892107
Wright High School,Charter,583.0,1800.0,83.682222,83.955000,93.333333,96.611111,90.333333
Thomas High School,Charter,638.0,1635.0,83.418349,83.848930,93.272171,97.308869,90.948012
Griffin High School,Charter,625.0,1468.0,83.351499,83.816757,93.392371,97.138965,90.599455
Pena High School,Charter,609.0,962.0,83.839917,84.044699,94.594595,95.945946,90.540541
Holden High School,Charter,581.0,427.0,83.803279,83.814988,92.505855,96.252927,89.227166